spring:
  main:
    banner-mode: off
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
      
keycloak:
  realm: 'Blog'
  auth-server-url: 'http://localhost:8180/auth'
  ssl-required: external
  resource: 'blog-api'
  use-resource-role-mappings: true
  bearer-only: true