spring:
  h2.console:
    enabled: true
    path: /console
    settings.web-allow-others: true
  datasource.url: jdbc:h2:file:/D:/Workspace/blog/blog-db-dev2
  
management:
  endpoints:
    web:
      exposure:
        include: '*'