spring:
  main:
    banner-mode: off
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
      
keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'Blog'
  resource: 'blog-api'
  ssl-required: external
  credentials:
    secret: 34d7bb89-2c05-4d41-ad8c-adfeb2e46989
  use-resource-role-mappings: true
  bearer-only: true